### ISSUE TITLE
Missing 'pry' on production install

### ISSUE THREAD

**Issue by ColonelPanics** [openflighthpc/power-client#2]
I've installed as per the README however the command will fail to execute due to the pry gem not being installed. It is expected for it not to be installed as the pry gem is for development only.

```
[root@localhost power-client]# bin/power status node01
Traceback (most recent call last):
	9: from bin/power:34:in `<main>'
	8: from /opt/flight/opt/runway/embedded/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
	7: from /opt/flight/opt/runway/embedded/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
	6: from /opt/flight/opt/runway/embedded/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
	5: from /opt/flight/opt/runway/embedded/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
	4: from /opt/flight/opt/runway/embedded/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
	3: from /opt/flight/opt/runway/embedded/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
	2: from /opt/flight/opt/runway/embedded/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
	1: from /opt/flight/opt/power-client/Rakefile:37:in `block in <top (required)>'
/opt/flight/opt/power-client/Rakefile:37:in `require': cannot load such file -- pry (LoadError)
```

## Steps to reproduce

The instructions I'm following (to use flight-runway ruby) are as follows:

```
yum install https://s3.eu-west-2.amazonaws.com/repo.openflighthpc.org/openflight/centos/7/x86_64/openflighthpc-release-2-1.noarch.rpm
yum install flight-runway

cd /opt/flight/opt/
git clone https://github.com/openflighthpc/power-client

cd power-client
export PATH=/opt/flight/bin:$PATH
bundle install --without development test --path vendor

cat << EOF > etc/config.yaml
base_url: http://localhost:1234
jwt_token: mygeneratedtokengoeshere
EOF
```

**Comment by WilliamMcCumstie** [comment]
It appears I never got around to building a `debug` mode into `power-client`. The error is cropping up in the rakefile:
https://github.com/openflighthpc/power-client/blob/1af9d7897d7c5bf1810442286586c657a779d5f1/Rakefile#L37

It needs to be implemented along these lines:

https://github.com/openflighthpc/render-client/blob/2b4b8c78c8bb7ad281520f557b160c728c2a0e27/Rakefile#L43-L46

https://github.com/openflighthpc/render-client/blob/2b4b8c78c8bb7ad281520f557b160c728c2a0e27/etc/config.yaml.reference#L23-L27
